### ISSUE TITLE
Message notifications sent by email unclear on how to react

### ISSUE THREAD

**Issue by ChMat** [claroline/MessageBundle#21]
Hi,

By default, email notifications about messages sent to the user are pretty unclear on how the user can interact with the person who wrote the message.

At the moment:
- replying by email sends an email either to someone unrelated to the conversation or to a noreply address
- if the user is new to Claroline, there is no link back to the Claroline instance.

I would suggest to implement the following:
- set the reply-to header to the email address of the person who actually sent the message (nice to reduce the probability of the email being marked as spam)
- modify the notification layout (or create a specialized layout for email notifications about messages) to include a link back to the Claroline instance (or even better, a link to the message itself)

Do you like these ideas?

**Comment by ngodfraind** [comment]
I agree for both of them. I'm probably going to do them both today.

**Comment by ngodfraind** [comment]
Ok, the replyTo fiend is now populated thanks to the change: Claroline/CoreBundle@9e068da7bc52e7fe4f2eb5d941a73de088b2f7d1

You can change the email layout in the administration yourself. It's located in Administrations => Parameters => Mail => Layout.
You can change the layout according to the platform locale and you can add some placeholders. Does it allows you to solve you use case or does it needs to be improved further ?

**Comment by ngodfraind** [comment]
5.1.14 has been released with the fix.
