### ISSUE TITLE
For workspace managers, users list in new message receiver selection is not clear

### ISSUE THREAD

**Issue by ChMat** [claroline/MessageBundle#22]
Hi,

For workspace managers, the users list in the modal box for selecting users is not clear. How are the users added to the list? They don't seem to match workspaces or groups.

![image](https://cloud.githubusercontent.com/assets/1511740/10354491/b302dd80-6d60-11e5-9d42-7c94c6ccc028.png)

Thanks for clarifying.

**Comment by ngodfraind** [comment]
If you're admin, this is the list of every users.
Otherwise, this is the list of users you share a workspace with.

Something is going wrong is the behaviour is different.

**Comment by ChMat** [comment]
Hi,

Here is what the admin told me about how the users see their contacts:

> Pour chacun cela devrait être des dizaines d'utilisateurs alors que seulement quelques uns. 
> Je pense en fait que ce ne sont que ceux qui sont inscrits manuellement (gestionnaire ou collaborateur) et qui partage des espaces ensembles. Les étudiants inscrits par groupe ne sont pas pris en compte.

**Comment by ngodfraind** [comment]
Fixed by Claroline/CoreBundle@d9d0f783bf7397bd62207bfd2310a000f8c39a16
